#include <memory>
#include <string>
#include <vector>

namespace dpll {
class clause {
public:
  clause(){};
  ~clause(){};

  std::vector<int> data;

  int add(int d) {
    this->data.push_back(d);
    return 0;
  }
};

typedef std::shared_ptr<dpll::clause> clausePtr;

class clauseSet {
public:
  clauseSet() = default;
  clauseSet(std::string path) { read_from_cnf(path); }
  ~clauseSet() = default;

  int cla_count, var_count;
  std::vector<clausePtr> clause_vec;

  int read_from_cnf(std::string path);
};

typedef std::shared_ptr<dpll::clauseSet> clauseSetPtr;
} // namespace dpll

// void CNF_Save(ClaNode *head, FILE *DSS) {
//   if (!head || !DSS)
//     return;
//   ClaNode *cur = head;
//   fprintf(DSS, "c \tThis Binary Puzzle is generated by\nc \tthe algorithm "
//                "written by Shuhan Li\n");
//   fprintf(DSS, "p cnf %d %d\n", var_count, cla_count);
//   while (cur) {
//     for (int i = 0; i < cur->len; i++)
//       fprintf(DSS, "%d ", cur->data[i]);
//     fprintf(DSS, "0\n");
//     cur = cur->next;
//   }
//   return;
// }

// void RES_Write(FILE *DSW, ClaNode *head, int *(*DPLL)(ClaNode *)) {
//   if (!DSW)
//     return;
//   clock_t start = clock();
//   int *result = DPLL(head);
//   clock_t end = clock();
//   double period = (double)(end - start) / CLOCKS_PER_SEC * 1000;
//   if (!result)
//     fprintf(DSW, "s 0\nt %.0f\n", period);
//   else {
//     fprintf(DSW, "s 1\nv ");
//     for (int i = 1; i <= var_count; i++) {
//       int d = i * result[i];
//       if (d)
//         fprintf(DSW, "%d ", d);
//     }
//     fprintf(DSW, "\nt %.0f\n", period);
//   }
//   return;
// }